name: Flutter CI

on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: flutter pub get
      -  run: dart fix --apply
      -  run: dart format --set-exit-if-changed .
  
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: flutter pub get
      -  run: flutter analyze

  build_apk:
    name: Build Example Android APK artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd example && flutter pub get
      - run: cd example && flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: example-apk
          path: example/build/app/outputs/apk/release/app-release.apk

  build_web:
    name: Build Example web artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd example && flutter pub get
      - run: cd example && flutter build web --release
      - uses: actions/upload-artifact@v3
        with:
          name: example-web
          path: example/build/web/
  
#  build_cinema_example:
#    name: Build Cinema Example linux artifact
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: cd example_cinema && flutter pub get
#      - run: cd example_cinema && flutter build linux --release
#      - uses: actions/upload-artifact@v3
#        with:
#          name: example-cinema-linux
#          path: example/build/linux/release/bundle/